# Generated by Django 4.1 on 2022-09-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlistitem',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='release_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='review',
            field=models.TextField(),
        ),
    ]
