# Generated by Django 4.1 on 2022-09-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0002_alter_watchlistitem_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlistitem',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='release_date',
            field=models.DateField(default='0000-00-00'),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='review',
            field=models.TextField(default=''),
        ),
    ]
